-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "cleanup_runs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "source" TEXT not null,
  "mode" TEXT not null default 'trash',
  "item_count" INTEGER not null default 0,
  "failed_count" INTEGER not null default 0,
  "freed_bytes" INTEGER not null default 0,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
