-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "protected_paths" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "path" TEXT not null,
  "reason" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "protected_paths_path_unique" ON "protected_paths" ("path");
