#!/usr/bin/env bun
/* eslint-disable ts/no-top-level-await, no-console */
/**
 * Package SystemCleaner as a self-contained macOS `.app`, and optionally a
 * `.dmg`.
 *
 * Why this is not `buddy build:desktop` + `buddy build:dmg`
 * --------------------------------------------------------
 * Those commands are the right tool for a hosted Stacks application: they
 * compile the framework launcher, which opens a Craft window on `DESKTOP_URL`,
 * and wrap it with the Craft runtime. Everything the app shows comes off the
 * network.
 *
 * SystemCleaner has no server to point at. It reads the disks, processes, and
 * login items of the Mac it is installed on, so the thing behind the window has
 * to run locally. `buddy build:dmg` copies exactly three files into the bundle
 * (`stacks-desktop`, `craft-runtime`, `desktop.json`) and has nowhere to put
 * the agent server or the UI payload this app needs.
 *
 * Everything that *is* framework work still goes through buddy:
 * `buddy build:views` renders the UI, and `database/migrations/` — generated by
 * `buddy migrate:regenerate` from `app/Models/` — is what creates the tables on
 * first launch.
 *
 * Layout produced
 * ---------------
 *   SystemCleaner.app/Contents/
 *     Info.plist
 *     MacOS/SystemCleaner            compiled app/Desktop/launcher.ts
 *     MacOS/system-cleaner-agent     compiled app/Desktop/server.ts
 *     MacOS/system-cleaner-scan      compiled app/Workers/disk-scan.ts
 *     MacOS/craft-runtime            the Craft native binary
 *     Resources/AppIcon.icns
 *     Resources/web/                 buddy build:views output
 *     Resources/migrations/          database/migrations
 *
 * Signing
 * -------
 * Set `DESKTOP_SIGNING_IDENTITY` to a Developer ID Application identity to get
 * a signed bundle, and add `NOTARY_PROFILE` to notarize and staple the DMG.
 * Unset, the build still succeeds and produces an unsigned bundle — useful
 * locally, not distributable (Gatekeeper will refuse it on another Mac).
 *
 * Deliberately Developer ID rather than Mac App Store: the App Store requires
 * `com.apple.security.app-sandbox`, and a sandboxed process cannot read
 * `~/Library`, enumerate `/Applications`, signal other processes, or exec
 * `brew` — which is most of this app.
 */

import { spawnSync } from 'node:child_process'
import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import process from 'node:process'

const ROOT = process.cwd()
const APP_NAME = process.env.DESKTOP_APP_NAME || 'SystemCleaner'
const BUNDLE_ID = process.env.DESKTOP_BUNDLE_ID || 'org.stacksjs.system-cleaner'
const MIN_MACOS = process.env.DESKTOP_MINIMUM_MACOS || '13.0'
const SIGNING_IDENTITY = process.env.DESKTOP_SIGNING_IDENTITY || ''
const NOTARY_PROFILE = process.env.NOTARY_PROFILE || ''

const OUT_DIR = path.join(ROOT, 'storage/framework/desktop-dist')
const APP_DIR = path.join(OUT_DIR, `${APP_NAME}.app`)
const CONTENTS = path.join(APP_DIR, 'Contents')
const MACOS_DIR = path.join(CONTENTS, 'MacOS')
const RESOURCES_DIR = path.join(CONTENTS, 'Resources')

const wantDmg = process.argv.includes('--dmg')

if (process.platform !== 'darwin') {
  console.error('[desktop] SystemCleaner only builds on macOS')
  process.exit(1)
}

const version = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8')).version || '0.0.0'

function run(cmd: string, args: string[], env?: Record<string, string>): void {
  const result = spawnSync(cmd, args, {
    stdio: 'inherit',
    cwd: ROOT,
    env: env ? { ...process.env, ...env } : process.env,
  })
  if (result.status !== 0)
    throw new Error(`${cmd} ${args.join(' ')} exited with ${result.status}`)
}

/**
 * Locate the Craft runtime.
 *
 * `CRAFT_BIN` wins, then the pantry install this project declares in
 * `deps.yaml`, then whatever is on PATH. Same precedence the framework's own
 * `resolveCraftBinary` uses, so a machine set up for `buddy build:desktop`
 * needs no extra configuration for this.
 */
function resolveCraft(): string {
  if (process.env.CRAFT_BIN && fs.existsSync(process.env.CRAFT_BIN))
    return process.env.CRAFT_BIN

  const pantryDir = path.join(ROOT, 'pantry/craft-native.org')
  if (fs.existsSync(pantryDir)) {
    // Newest installed version wins, so an upgrade does not need editing here.
    const versions = fs.readdirSync(pantryDir).filter(v => v.startsWith('v')).sort().reverse()
    for (const v of versions) {
      const candidate = path.join(pantryDir, v, 'bin/craft')
      if (fs.existsSync(candidate))
        return candidate
    }
  }

  const onPath = Bun.which('craft')
  if (onPath)
    return onPath

  throw new Error(
    'Craft runtime not found. Install it with `pantry install craft`, or point CRAFT_BIN at the binary.',
  )
}

function copyDir(from: string, to: string): void {
  fs.cpSync(from, to, { recursive: true })
}

// ── 1. Render the UI ────────────────────────────────────────────
// SYSTEM_CLEANER_AGENT=1 is what makes `resources/layouts/app.stx` render the
// real app shell. Without it a production build renders the "runs on your Mac"
// download prompt, which is correct for the website and useless in the bundle.
console.log('[desktop] building views')
// The STX page cache is keyed on the template, not on the environment that
// rendered it, so a cached page from a marketing build would ship the
// "runs on your Mac" prompt inside the app itself. Dropping the cache is
// cheap (a full render is ~3s) next to shipping the wrong payload.
for (const cache of ['.stx', 'storage/framework/stx', 'dist'])
  fs.rmSync(path.join(ROOT, cache), { recursive: true, force: true })

run('./buddy', ['build:views'], {
  APP_ENV: 'production',
  NODE_ENV: 'production',
  SYSTEM_CLEANER_AGENT: '1',
})

const webSource = path.join(ROOT, 'dist')
if (!fs.existsSync(path.join(webSource, 'app/large-files.html')))
  throw new Error(`View build did not produce the app pages in ${webSource}`)

// ── 2. Assemble the bundle skeleton ─────────────────────────────
fs.rmSync(APP_DIR, { recursive: true, force: true })
fs.mkdirSync(MACOS_DIR, { recursive: true })
fs.mkdirSync(RESOURCES_DIR, { recursive: true })

console.log('[desktop] compiling agent server')
run('bun', [
  'build', path.join(ROOT, 'app/Desktop/server.ts'),
  '--compile', '--target=bun-darwin-arm64',
  '--outfile', path.join(MACOS_DIR, 'system-cleaner-agent'),
])

// The scanner is its own binary because `bun build --compile` does not embed
// Worker entrypoints; the pool spawns it as a child process. See the note at
// the top of app/Workers/disk-scan.ts.
console.log('[desktop] compiling scanner')
run('bun', [
  'build', path.join(ROOT, 'app/Workers/disk-scan.ts'),
  '--compile', '--target=bun-darwin-arm64',
  '--outfile', path.join(MACOS_DIR, 'system-cleaner-scan'),
])

console.log('[desktop] compiling launcher')
run('bun', [
  'build', path.join(ROOT, 'app/Desktop/launcher.ts'),
  '--compile', '--target=bun-darwin-arm64',
  '--outfile', path.join(MACOS_DIR, APP_NAME),
])

const craft = resolveCraft()
console.log(`[desktop] bundling Craft runtime from ${craft}`)
fs.copyFileSync(craft, path.join(MACOS_DIR, 'craft-runtime'))
fs.chmodSync(path.join(MACOS_DIR, 'craft-runtime'), 0o755)

copyDir(webSource, path.join(RESOURCES_DIR, 'web'))
copyDir(path.join(ROOT, 'database/migrations'), path.join(RESOURCES_DIR, 'migrations'))

// ── 3. Icon ─────────────────────────────────────────────────────
const ICON_SIZES = [16, 32, 128, 256, 512] as const

/**
 * Build `AppIcon.icns`.
 *
 * `buddy generate:app-icons` already rendered every macOS size from
 * `config/images.ts`, so the preferred path just renames that set into the
 * `.iconset` layout `iconutil` expects. Scaling from the 1024px master with
 * `sips` is the fallback for a checkout where the icons have not been
 * generated yet.
 */
function buildIcon(): boolean {
  const scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'system-cleaner-icon-'))
  const iconset = path.join(scratch, 'icon.iconset')
  fs.mkdirSync(iconset, { recursive: true })

  const generated = path.join(ROOT, 'resources/assets/images/AppIcon.appiconset')
  let populated = false

  if (fs.existsSync(generated)) {
    for (const size of ICON_SIZES) {
      for (const [suffix, name] of [
        ['', `icon_${size}x${size}.png`],
        ['@2x', `icon_${size}x${size}@2x.png`],
      ] as const) {
        const from = path.join(generated, `AppIcon-${size}${suffix}.png`)
        if (fs.existsSync(from)) {
          fs.copyFileSync(from, path.join(iconset, name))
          populated = true
        }
      }
    }
  }

  if (!populated) {
    const master = [
      path.join(ROOT, 'public/images/app-icon.png'),
      path.join(ROOT, 'resources/assets/images/app-icon.png'),
    ].find(candidate => fs.existsSync(candidate))

    if (!master) {
      fs.rmSync(scratch, { recursive: true, force: true })
      console.warn('[desktop] no app icon found; run `./buddy generate:app-icons`')
      return false
    }

    for (const size of ICON_SIZES) {
      for (const [dimension, name] of [
        [size, `icon_${size}x${size}.png`],
        [size * 2, `icon_${size}x${size}@2x.png`],
      ] as const) {
        spawnSync('sips', ['-z', String(dimension), String(dimension), master, '--out', path.join(iconset, name)], {
          stdio: 'ignore',
        })
      }
    }
  }

  const icns = path.join(RESOURCES_DIR, 'AppIcon.icns')
  const result = spawnSync('iconutil', ['-c', 'icns', iconset, '-o', icns], { stdio: 'inherit' })
  fs.rmSync(scratch, { recursive: true, force: true })
  return result.status === 0 && fs.existsSync(icns)
}

const hasIcon = buildIcon()

// ── 4. Info.plist ───────────────────────────────────────────────
// NSAppTransportSecurity allows loopback only: the window talks to the agent
// on 127.0.0.1 over plain HTTP, and nothing else needs an exception. The
// framework's own DMG plist sets NSAllowsArbitraryLoads, which would also
// permit every unencrypted host on the internet.
fs.writeFileSync(path.join(CONTENTS, 'Info.plist'), `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>${APP_NAME}</string>
  <key>CFBundleDisplayName</key><string>${APP_NAME}</string>
  <key>CFBundleIdentifier</key><string>${BUNDLE_ID}</string>
  <key>CFBundleVersion</key><string>${version}</string>
  <key>CFBundleShortVersionString</key><string>${version}</string>
  <key>CFBundleExecutable</key><string>${APP_NAME}</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>LSApplicationCategoryType</key><string>public.app-category.utilities</string>
  <key>LSMinimumSystemVersion</key><string>${MIN_MACOS}</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>NSAppTransportSecurity</key>
  <dict>
    <key>NSAllowsLocalNetworking</key><true/>
    <key>NSExceptionDomains</key>
    <dict>
      <key>127.0.0.1</key>
      <dict><key>NSExceptionAllowsInsecureHTTPLoads</key><true/></dict>
    </dict>
  </dict>
  <!-- Shown in the Full Disk Access prompt. The app cannot report on caches,
       login items, or application support without it. -->
  <key>NSSystemAdministrationUsageDescription</key>
  <string>${APP_NAME} needs access to your files to report what is using disk space and to remove what you choose to remove.</string>
  <key>NSDesktopFolderUsageDescription</key>
  <string>${APP_NAME} scans your Desktop for large files.</string>
  <key>NSDocumentsFolderUsageDescription</key>
  <string>${APP_NAME} scans your Documents for large files.</string>
  <key>NSDownloadsFolderUsageDescription</key>
  <string>${APP_NAME} scans your Downloads for large files.</string>
  <key>NSAppleEventsUsageDescription</key>
  <string>${APP_NAME} asks Finder to move items to the Trash so deletions stay recoverable.</string>${hasIcon ? '\n  <key>CFBundleIconFile</key><string>AppIcon</string>' : ''}
</dict>
</plist>
`)

// ── 5. Sign ─────────────────────────────────────────────────────
if (SIGNING_IDENTITY) {
  console.log(`[desktop] signing with ${SIGNING_IDENTITY}`)
  // Inside-out: nested executables first, the bundle last. Signing the bundle
  // first invalidates the seal as soon as an inner binary is re-signed.
  for (const target of [
    path.join(MACOS_DIR, 'craft-runtime'),
    path.join(MACOS_DIR, 'system-cleaner-scan'),
    path.join(MACOS_DIR, 'system-cleaner-agent'),
    path.join(MACOS_DIR, APP_NAME),
    APP_DIR,
  ]) {
    run('codesign', [
      '--force',
      '--options', 'runtime',
      '--timestamp',
      '--sign', SIGNING_IDENTITY,
      target,
    ])
  }
  run('codesign', ['--verify', '--deep', '--strict', '--verbose=2', APP_DIR])
}
else {
  console.warn('[desktop] DESKTOP_SIGNING_IDENTITY is unset — the bundle is unsigned and will not launch on another Mac')
}

const bundleBytes = spawnSync('du', ['-sk', APP_DIR], { encoding: 'utf8' }).stdout?.trim().split(/\s+/)[0]
console.log(`[desktop] ${APP_DIR} (${((Number(bundleBytes) || 0) / 1024).toFixed(1)} MB)`)

// ── 6. DMG ──────────────────────────────────────────────────────
if (wantDmg) {
  const staging = fs.mkdtempSync(path.join(os.tmpdir(), 'system-cleaner-dmg-'))
  fs.cpSync(APP_DIR, path.join(staging, `${APP_NAME}.app`), { recursive: true })
  fs.symlinkSync('/Applications', path.join(staging, 'Applications'))

  const dmgPath = path.join(OUT_DIR, `${APP_NAME}-${version}.dmg`)
  fs.rmSync(dmgPath, { force: true })
  run('hdiutil', [
    'create', '-volname', APP_NAME,
    '-srcfolder', staging,
    '-ov', '-format', 'UDZO',
    dmgPath,
  ])
  fs.rmSync(staging, { recursive: true, force: true })

  if (SIGNING_IDENTITY)
    run('codesign', ['--force', '--sign', SIGNING_IDENTITY, dmgPath])

  if (NOTARY_PROFILE) {
    console.log('[desktop] submitting to the notary service')
    run('xcrun', ['notarytool', 'submit', dmgPath, '--keychain-profile', NOTARY_PROFILE, '--wait'])
    run('xcrun', ['stapler', 'staple', dmgPath])
  }
  else {
    console.warn('[desktop] NOTARY_PROFILE is unset — the DMG is not notarized')
  }

  console.log(`[desktop] ${dmgPath}`)
}
